sudo: false
dist: trusty
language: node_js
node_js:
  - "7"
  - "8"
  - "9"
  - "10"
install:
  - npm install
script: npm run lint && npm test
git:
  submodules: false
deploy:
  provider: npm
  email: development@hive.pt
  api_key:
    secure: ZhIwFDnzMZ81g2aRqXmgpjdYYRTGjvE0VX7UZJ/DW9H1hC7pTmJmGrZVw+sAJKtLkWfUfsFEcqt8tNvBje4+y5gyIuDVqq79gsJqoI6i0DdbaH9MIReLbXUR5gnMPWrzIpyP9Wqk/BuzgLAnKDPjzXGzGGEpukVjIjGOHayXaNk=
  on:
    tags: true
    node_js: "7"
